### PR TITLE
Add Information & PowerControl endpoints

### PR DESCRIPTION
**Pull request by rubenelshof**
Added Information & PowerControl proto files, Protocol Buffers and solaredge.py

Tested with curl but please check prior to merge.

### CODE REVIEW

**Comment by rubenelshof** [comment]
No problem. I put it in as draft as I wasnt sure if these endpoint were wanted.
I will put it as ready for review after updating the readme.
I am planning to also add the Communication endpoint as that seems to be the last one.

**Comment by rubenelshof** [comment]
@drobtravels Please do not merge yet. Not 100% satisfied with some of the output.

**Comment by rubenelshof** [comment]
@drobtravels Made some changes. Please re-review and after that it can be merged.

**Comment by drobtravels** [comment]
published 0.2.0

**Pull request merged**
